### ISSUE TITLE
No Graph

### ISSUE THREAD

**Issue by ivancheng111** [abraker95/ultimate_osu_analyzer#38]
Sorry if this is a stupid question but,
![Screenshot (704)](https://user-images.githubusercontent.com/57711268/117540913-663e9780-b037-11eb-8c74-d1e0b44d4ded.png)
![Screenshot (705)](https://user-images.githubusercontent.com/57711268/117540915-69d21e80-b037-11eb-883c-e0b1c7a5d1f4.png)
I can't make graphs.

**Comment by abraker95** [comment]
Those menu options were supposed to be removed in favor of scripts you can run in the console tab like so:
```
CmdUtils.run_script('scripts/std_hit_offsets.py', globals(), locals())
window = StdHitOffsets().run()
```

See scripts folder for all the runnable scripts.

**Comment by ivancheng111** [comment]
Ah alright thanks.
